FROM openjdk:18
COPY ./target/site1-0.0.1-SNAPSHOT.jar /app/site1-0.0.1-SNAPSHOT.jar
COPY ./credentials/sujansproject-d56bad671645.json /credentials/sujansproject-d56bad671645.json
ENV GOOGLE_APPLICATION_CREDENTIALS="/credentials/sujansproject-d56bad671645.json"

WORKDIR /app
EXPOSE 9080
ENTRYPOINT ["java", "-jar", "site1-0.0.1-SNAPSHOT.jar"]