FROM openjdk:18
WORKDIR /app
COPY ./entrypoint.sh /app/entrypoint.sh
COPY ./target/site1-0.0.1-SNAPSHOT.jar /app/app.jar
COPY ./credentials/ivory-cycle-412111-b5503cd575ba.json /credentials/ivory-cycle-412111-b5503cd575ba.json
ENV GOOGLE_APPLICATION_CREDENTIALS="/credentials/ivory-cycle-412111-b5503cd575ba.json"
EXPOSE 9080
ENTRYPOINT ["/app/entrypoint.sh"]